name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build --no-daemon  # Gradle을 사용하여 빌드

      - name: Build Docker image
        run: docker build . -t hamgeonwook/4zopalza_back:latest

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push hamgeonwook/4zopalza_back:latest

  dispatch:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Trigger repository dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.GH_PAT }}
            repository: React-4/dockercompose
            event-type: trigger-workflow
